package com.mirror.recorder.gui;
import com.mirror.recorder.manager.RecorderManager;import net.minecraft.client.gui.*;import org.lwjgl.input.Mouse;import java.io.IOException;
public class GuiMirrorDuplicate extends GuiScreen{

    private static final int CANCEL=20,PREV=21,NEXT=22,PAGE_SIZE=10,MAX_SLOT=100;private final GuiMirrorSlotTools parent;private final RecorderManager manager;private final int source;private int wx,wy,ww,wh,page;
    public GuiMirrorDuplicate(GuiMirrorSlotTools p,RecorderManager m,int s){parent=p;manager=m;source=s;page=Math.max(0,Math.min(9,(s-1)/PAGE_SIZE));}
    @Override public void initGui(){buttonList.clear();ww=Math.min(width-20,430);wh=Math.min(188,height-8);wx=(width-ww)/2;wy=Math.max(0,(height-wh)/2);int gap=6,x=wx+18,w=ww-36,cell=(w-gap*4)/5,from=page*PAGE_SIZE+1;for(int n=0;n<PAGE_SIZE;n++){int slot=from+n,col=n%5,row=n/5;StyledButton b=new StyledButton(101+n,x+col*(cell+gap),wy+55+row*27,cell,21,(Lang.s("Слот ","Slot ","Слот ","Slot ","Slot "))+slot).accent(UiTheme.PURPLE);b.enabled=slot!=source&&manager.getSlotFrameCount(slot)==0&&!manager.isSlotBusy(slot);b.tip(Lang.s("§fСлот "+slot,"§fSlot "+slot,"§fСлот "+slot,"§fSlot "+slot,"§fSlot "+slot),Lang.s("§7Сюда положим копию записи.","§7The copy will be placed here.","§7Сюди покладемо копію запису.","§7Hierhin legen wir die Kopie der Aufnahme.","§7Tutaj umieścimy kopię nagrania."),Lang.s("§8Оригинал останется на месте.","§8The original stays where it is.","§8Оригінал залишиться на місці.","§8Das Original bleibt, wo es ist.","§8Oryginał zostaje na miejscu."));buttonList.add(b);}int navW=28;StyledButton prev=new StyledButton(PREV,x,wy+124,navW,19,"‹").accent(UiTheme.GRAY).tip(Lang.s("§fНазад","§fBack","§fНазад","§fZurück","§fWstecz"),Lang.s("§7Показать предыдущие 10 слотов.","§7Show the previous 10 slots.","§7Показати попередні 10 слотів.","§7Die vorherigen 10 Slots anzeigen.","§7Pokaż poprzednie 10 slotów.")),next=new StyledButton(NEXT,x+w-navW,wy+124,navW,19,"›").accent(UiTheme.GRAY).tip(Lang.s("§fДальше","§fNext","§fДалі","§fWeiter","§fDalej"),Lang.s("§7Показать следующие 10 слотов.","§7Show the next 10 slots.","§7Показати наступні 10 слотів.","§7Die nächsten 10 Slots anzeigen.","§7Pokaż następne 10 slotów."));prev.enabled=page>0;next.enabled=page<9;buttonList.add(prev);buttonList.add(next);buttonList.add(new StyledButton(CANCEL,x,wy+wh-28,w,20,Lang.t("common.cancel")).accent(UiTheme.GRAY).tip(Lang.s("§fОтмена","§fCancel","§fСкасувати","§fAbbrechen","§fAnuluj"),Lang.s("§7Копия создана не будет.","§7No copy will be made.","§7Копія створена не буде.","§7Es wird keine Kopie erstellt.","§7Kopia nie zostanie utworzona.")));}
    @Override public void drawScreen(int mx,int my,float pt){{int bd=UiTheme.GLASS_BACKDROP;drawGradientRect(0,0,width,height,bd,bd);}UiTheme.window(wx,wy,wx+ww,wy+wh,32);UiTheme.drawFitted(fontRenderer,Lang.s("§lКуда копировать слот "+source+"?","§lCopy slot "+source+" where?","§lКуди копіювати слот "+source+"?","§lWohin soll Slot "+source+" kopiert werden?","§lDokąd skopiować slot "+source+"?"),wx+15,wy+11,ww-30,UiTheme.TEXT);UiTheme.drawFitted(fontRenderer,Lang.s("Занятые и активные слоты недоступны","Busy and active slots are unavailable","Зайняті й активні слоти недоступні","Belegte und aktive Slots sind nicht verfügbar","Zajęte i aktywne sloty są niedostępne"),wx+18,wy+39,ww-36,UiTheme.TEXT_MUTE);drawCenteredString(fontRenderer,(page+1)+" / 10  ·  "+(page*10+1)+"–"+(page*10+10),wx+ww/2,wy+128,UiTheme.TEXT_DIM);super.drawScreen(mx,my,pt);UiTheme.buttonTooltip(fontRenderer,buttonList,mx,my,width,height);}
    @Override protected void actionPerformed(GuiButton b)throws IOException{if(b.id==CANCEL){mc.displayGuiScreen(parent);return;}if(b.id==PREV&&page>0){page--;initGui();return;}if(b.id==NEXT&&page<9){page++;initGui();return;}if(b.id>=101&&b.id<=110){int target=page*PAGE_SIZE+(b.id-100);if(manager.duplicateSlot(source,target))parent.finish(Lang.s("§aСлот ","§aSlot ","§aСлот ","§aSlot ","§aSlot ")+source+Lang.s(" скопирован в слот "," copied to slot "," скопійовано в слот "," kopiert in Slot "," skopiowany do slotu ")+target);else parent.finish(Lang.s("§cКопирование не выполнено","§cCopy failed","§cКопіювання не виконано","§cKopieren fehlgeschlagen","§cKopiowanie nie powiodło się"));}}
    @Override public void handleMouseInput()throws IOException{super.handleMouseInput();int wheel=Mouse.getEventDWheel();if(wheel<0&&page<9){page++;initGui();}else if(wheel>0&&page>0){page--;initGui();}}
    @Override protected void keyTyped(char c,int k)throws IOException{if(k==1){mc.displayGuiScreen(parent);return;}super.keyTyped(c,k);}@Override public boolean doesGuiPauseGame(){return false;}
}
