package com.mirror.recorder.gui;
import com.mirror.recorder.manager.RecorderManager;
import net.minecraft.client.gui.*;
import org.lwjgl.input.Keyboard;
import java.io.IOException;

public class GuiMirrorEdit extends GuiScreen{

    private static final int SAVE=1,CANCEL=2,DELAY_DEC=3,DELAY_INC=4;
    private final GuiMirrorSlotTools parent;private final RecorderManager manager;private final int slot;
    private CenteredTextField name,desc;private int wx,wy,ww,wh,delay;private String error="";
    public GuiMirrorEdit(GuiMirrorSlotTools p,RecorderManager m,int s){parent=p;manager=m;slot=s;}
    @Override public void initGui(){
        Keyboard.enableRepeatEvents(true);buttonList.clear();ww=Math.min(width-20,410);wh=Math.min(238,height-8);wx=(width-ww)/2;wy=Math.max(0,(height-wh)/2);delay=manager.getSlotStartDelay(slot);
        // Поле покрывает видимую рамку (wy+65..wy+88 и wy+113..wy+136): CenteredTextField рисует текст по вертикальному центру.
        name=new CenteredTextField(10,fontRenderer,wx+27,wy+65,ww-54,23);name.setMaxStringLength(40);name.setText(manager.getSlotName(slot));name.setFocused(true);
        desc=new CenteredTextField(11,fontRenderer,wx+27,wy+113,ww-54,23);desc.setMaxStringLength(120);desc.setText(manager.getSlotDescription(slot));
        int sy=wy+158,bs=20,vw=48,right=wx+ww-20;buttonList.add(new StyledButton(DELAY_DEC,right-vw-bs*2,sy,bs,bs,"−").flat().compact().tip(Lang.s("§fМеньше пауза","§fLess delay","§fМенша пауза","§fKürzere Pause","§fKrótsza pauza"),Lang.s("§7Секундой меньше ждать перед стартом.","§7Wait one second less before the start.","§7Секундою менше чекати перед стартом.","§7Eine Sekunde weniger vor dem Start warten.","§7Sekundę mniej czekać przed startem."),Lang.s("§8Зажмите Ctrl — сразу на 5 секунд.","§8Hold Ctrl to change by 5 seconds at once.","§8Затисніть Ctrl — одразу на 5 секунд.","§8Halte Ctrl — gleich um 5 Sekunden.","§8Przytrzymaj Ctrl — od razu o 5 sekund.")));buttonList.add(new StyledButton(DELAY_INC,right-bs,sy,bs,bs,"+").flat().compact().tip(Lang.s("§fБольше пауза","§fMore delay","§fБільша пауза","§fLängere Pause","§fDłuższa pauza"),Lang.s("§7Секундой больше ждать перед стартом.","§7Wait one second more before the start.","§7Секундою більше чекати перед стартом.","§7Eine Sekunde länger vor dem Start warten.","§7Sekundę dłużej czekać przed startem."),Lang.s("§8Зажмите Ctrl — сразу на 5 секунд.","§8Hold Ctrl to change by 5 seconds at once.","§8Затисніть Ctrl — одразу на 5 секунд.","§8Halte Ctrl — gleich um 5 Sekunden.","§8Przytrzymaj Ctrl — od razu o 5 sekund.")));
        int half=(ww-47)/2,y=wy+wh-31;buttonList.add(new StyledButton(CANCEL,wx+20,y,half,20,Lang.s("Отмена","Cancel","Скасувати","Abbrechen","Anuluj")).accent(UiTheme.GRAY).tip(Lang.s("§fОтмена","§fCancel","§fСкасувати","§fAbbrechen","§fAnuluj"),Lang.s("§7Закроет окно и ничего не поменяет.","§7Closes the window and changes nothing.","§7Закриє вікно і нічого не змінить.","§7Schließt das Fenster und ändert nichts.","§7Zamyka okno i niczego nie zmienia.")));buttonList.add(new StyledButton(SAVE,wx+27+half,y,half,20,Lang.s("Сохранить","Save","Зберегти","Speichern","Zapisz")).primary().accent(UiTheme.GREEN).tip(Lang.s("§fСохранить","§fSave","§fЗберегти","§fSpeichern","§fZapisz"),Lang.s("§7Запомнит имя, описание и паузу для этой записи.","§7Remembers the name, description and delay for this recording.","§7Запам'ятає ім'я, опис і паузу для цього запису.","§7Merkt sich Name, Beschreibung und Pause für diese Aufnahme.","§7Zapamięta nazwę, opis i pauzę dla tego nagrania.")));
    }
    @Override public void drawScreen(int mx,int my,float pt){
        {int bd=UiTheme.GLASS_BACKDROP;drawGradientRect(0,0,width,height,bd,bd);}UiTheme.window(wx,wy,wx+ww,wy+wh,34);UiTheme.header(fontRenderer,wx,wy,wx+ww,34,Lang.s("Слот ","Slot ","Слот ","Slot ","Slot ")+slot,Lang.s("Название, описание и задержка","Name, description and delay","Назва, опис і затримка","Name, Beschreibung und Verzögerung","Nazwa, opis i opóźnienie"),UiTheme.ACCENT);
        UiTheme.card(wx+14,wy+44,wx+ww-14,wy+190,UiTheme.CARD,UiTheme.BORDER);
        label(Lang.s("Название","Name","Назва","Name","Nazwa"),name.getText().length()+"/40",wy+54);UiTheme.inset(wx+20,wy+65,wx+ww-20,wy+88);name.drawTextBox();
        label(Lang.s("Описание","Description","Опис","Beschreibung","Opis"),desc.getText().length()+"/120",wy+102);UiTheme.inset(wx+20,wy+113,wx+ww-20,wy+136);desc.drawTextBox();
        int bs=20,vw=48,right=wx+ww-20,vx=right-vw-bs*2;UiTheme.card(vx,wy+158,right,wy+178,UiTheme.DEEP,UiTheme.BORDER);
        UiTheme.drawFitted(fontRenderer,Lang.s("Задержка перед стартом","Start delay","Затримка перед стартом","Startverzögerung","Opóźnienie przed startem"),wx+22,wy+162,Math.max(24,vx-wx-28),UiTheme.TEXT);
        UiTheme.drawFitted(fontRenderer,Lang.s("0–60 секунд","0–60 seconds","0–60 секунд","0–60 Sekunden","0–60 sekund"),wx+22,wy+174,Math.max(24,vx-wx-28),UiTheme.TEXT_MUTE);
        UiTheme.drawCenteredFitted(fontRenderer,delay+(Lang.s(" с"," s"," с"," s"," s")),vx+bs+vw/2f,wy+164,vw-4,UiTheme.TEXT,false);
        if(!error.isEmpty())UiTheme.drawCenteredFitted(fontRenderer,error,wx+ww/2f,wy+195,ww-28,UiTheme.RED,false);super.drawScreen(mx,my,pt);UiTheme.buttonTooltip(fontRenderer,buttonList,mx,my,width,height);if(mx>=wx+20&&mx<wx+ww-20&&my>=wy+65&&my<wy+88&&UiTheme.tipReady("editName"))UiTheme.tooltip(fontRenderer,new String[]{Lang.s("§fНазвание","§fName","§fНазва","§fName","§fNazwa"),Lang.s("§7Как запись будет называться в списке.","§7How the recording will be called in the list.","§7Як запис називатиметься у списку.","§7Wie die Aufnahme in der Liste heißen wird.","§7Jak nagranie będzie się nazywać na liście."),Lang.s("§8Например: «Путь на ферму».","§8For example: «Path to the farm».","§8Наприклад: «Шлях на ферму».","§8Zum Beispiel: «Weg zur Farm».","§8Na przykład: «Droga na farmę».")},mx,my,width,height);else if(mx>=wx+20&&mx<wx+ww-20&&my>=wy+113&&my<wy+136&&UiTheme.tipReady("editDesc"))UiTheme.tooltip(fontRenderer,new String[]{Lang.s("§fОписание","§fDescription","§fОпис","§fBeschreibung","§fOpis"),Lang.s("§7Пара слов, чтобы не перепутать похожие записи.","§7A few words to tell similar recordings apart.","§7Кілька слів, щоб не переплутати схожі записи.","§7Ein paar Worte, um ähnliche Aufnahmen zu unterscheiden.","§7Kilka słów, by nie pomylić podobnych nagrań."),Lang.s("§8Можно оставить пустым.","§8Can be left empty.","§8Можна залишити порожнім.","§8Kann leer bleiben.","§8Można zostawić puste.")},mx,my,width,height);
    }
    private void label(String left,String right,int y){fontRenderer.drawString(left,wx+22,y,UiTheme.TEXT_DIM);fontRenderer.drawString(right,wx+ww-22-fontRenderer.getStringWidth(right),y,UiTheme.TEXT_MUTE);}
    @Override public void updateScreen(){name.updateCursorCounter();desc.updateCursorCounter();}
    @Override protected void mouseClicked(int x,int y,int b)throws IOException{name.mouseClicked(x,y,b);desc.mouseClicked(x,y,b);super.mouseClicked(x,y,b);}
    @Override protected void keyTyped(char c,int k)throws IOException{if(k==1){mc.displayGuiScreen(parent);return;}if(k==Keyboard.KEY_TAB){boolean n=!name.isFocused();name.setFocused(n);desc.setFocused(!n);return;}if(k==Keyboard.KEY_RETURN||k==Keyboard.KEY_NUMPADENTER){save();return;}if(name.textboxKeyTyped(c,k))return;desc.textboxKeyTyped(c,k);}
    private void save(){boolean metaOk=manager.setSlotMetadata(slot,name.getText(),desc.getText()),delayOk=manager.setSlotStartDelay(slot,delay);if(metaOk&&delayOk){parent.finish("§a"+(Lang.s("Настройки слота "+slot+" обновлены","Slot "+slot+" settings updated","Налаштування слота "+slot+" оновлено","Einstellungen von Slot "+slot+" aktualisiert","Ustawienia slotu "+slot+" zaktualizowane")));return;}if(metaOk)error=Lang.s("Имя и описание сохранены, задержка — нет","Name and description saved, start delay was not","Ім'я та опис збережено, затримка — ні","Name und Beschreibung gespeichert, Verzögerung nicht","Nazwa i opis zapisane, opóźnienie — nie");else if(delayOk)error=Lang.s("Задержка сохранена, имя и описание — нет","Start delay saved, name and description were not","Затримка збережена, ім'я та опис — ні","Verzögerung gespeichert, Name und Beschreibung nicht","Opóźnienie zapisane, nazwa i opis — nie");else error=Lang.s("Не удалось сохранить настройки слота","Could not save the slot settings","Не вдалося зберегти налаштування слота","Slot-Einstellungen konnten nicht gespeichert werden","Nie udało się zapisać ustawień slotu");}
    @Override protected void actionPerformed(GuiButton b)throws IOException{if(b.id==SAVE)save();else if(b.id==DELAY_DEC)delay=Math.max(0,delay-(Keyboard.isKeyDown(Keyboard.KEY_LCONTROL)||Keyboard.isKeyDown(Keyboard.KEY_RCONTROL)?5:1));else if(b.id==DELAY_INC)delay=Math.min(60,delay+(Keyboard.isKeyDown(Keyboard.KEY_LCONTROL)||Keyboard.isKeyDown(Keyboard.KEY_RCONTROL)?5:1));else mc.displayGuiScreen(parent);}
    @Override public void onGuiClosed(){Keyboard.enableRepeatEvents(false);}@Override public boolean doesGuiPauseGame(){return false;}
}
