package com.mirror.recorder.gui;
import com.mirror.recorder.config.RecorderConfig;import net.minecraft.client.gui.*;import java.io.IOException;import java.util.*;
public final class GuiStabilizationSettings extends GuiScreen{

    private static final int MASTER=1,CURSOR=2,SKIP_DELAY=3,SAVE=4,CANCEL=5,POS_DEC=10,POS_INC=11,SPEED_DEC=12,SPEED_INC=13,TIME_DEC=14,TIME_INC=15;
    private final GuiScreen parent;private final RecorderConfig config;private int x,y,w,h,paramTop,rowH,paramStep=24;private boolean oldMaster,oldCursor,oldSkip,saved=false;private float oldPos,oldSpeed;private int oldTime;private StyledButton master,cursor,skip;private final List<StyledButton> dependent=new ArrayList<StyledButton>();
    public GuiStabilizationSettings(GuiScreen parent,RecorderConfig config){this.parent=parent;this.config=config;snapshot();}
    private void snapshot(){oldMaster=config.isAutoReturnEnabled();oldCursor=config.isCursorStabilization();oldSkip=config.isSkipLoopStartDelay();oldPos=config.getReturnPositionTolerance();oldSpeed=config.getReturnAlignSpeed();oldTime=config.getReturnTimeoutSeconds();}
    private void restore(){config.setAutoReturnEnabled(oldMaster);config.setCursorStabilization(oldCursor);config.setSkipLoopStartDelay(oldSkip);config.setReturnPositionTolerance(oldPos);config.setReturnAlignSpeed(oldSpeed);config.setReturnTimeoutSeconds(oldTime);}
    private boolean changed(){return oldMaster!=config.isAutoReturnEnabled()||oldCursor!=config.isCursorStabilization()||oldSkip!=config.isSkipLoopStartDelay()||oldPos!=config.getReturnPositionTolerance()||oldSpeed!=config.getReturnAlignSpeed()||oldTime!=config.getReturnTimeoutSeconds();}
    private StyledButton add(StyledButton b){buttonList.add(b);return b;}private StyledButton dep(StyledButton b){return add(b);}
    private void addStepper(int decId,int incId,int rowY,String title,String detail){int bw=22,chip=58,gap=4,right=x+w-16,incX=right-bw,chipX=incX-gap-chip,decX=chipX-gap-bw;dep(new StyledButton(decId,decX,rowY,bw,rowH,"\u2212").accent(UiTheme.GRAY).tip(Lang.s("§fМеньше: ","§fDecrease: ","§fМенше: ","§fWeniger: ","§fMniej: ")+title,detail,Lang.s("§8Нажмите, чтобы уменьшить значение.","§8Click to decrease the value.","§8Натисніть, щоб зменшити значення.","§8Klicken, um den Wert zu verringern.","§8Kliknij, aby zmniejszyć wartość.")));dep(new StyledButton(incId,incX,rowY,bw,rowH,"+").accent(UiTheme.GRAY).tip(Lang.s("§fБольше: ","§fIncrease: ","§fБільше: ","§fMehr: ","§fWięcej: ")+title,detail,Lang.s("§8Нажмите, чтобы увеличить значение.","§8Click to increase the value.","§8Натисніть, щоб збільшити значення.","§8Klicken, um den Wert zu erhöhen.","§8Kliknij, aby zwiększyć wartość.")));}
    @Override public void initGui(){buttonList.clear();dependent.clear();w=Math.min(width-20,390);h=Math.min(height-12,302);x=(width-w)/2;y=(height-h)/2;int left=x+16,fullW=w-32,toggleH=18,ty=y+48;
        master=add(new StyledButton(MASTER,left,ty,fullW,toggleH,Lang.s("Автовозврат Baritone","Baritone auto return","Автоповернення Baritone","Baritone-Auto-Rückkehr","Auto-powrót Baritone")).asToggle(config.isAutoReturnEnabled()).tip(Lang.s("§fВозврат в точку старта","§fReturn to the start point","§fПовернення в точку старту","§fRückkehr zum Startpunkt","§fPowrót do punktu startu"),Lang.s("§7Вкл: перед повтором мод сам приведёт вас туда, где начиналась запись.","§7On: before playback the mod walks you back to where the recording started.","§7Увімк: перед повтором мод сам приведе вас туди, де починався запис.","§7An: vor der Wiedergabe bringt die Mod dich dorthin zurück, wo die Aufnahme begann.","§7Wł: przed powtórką mod sam zaprowadzi cię tam, gdzie zaczęło się nagranie."),Lang.s("§7Выкл: повтор начнётся там, где вы стоите сейчас.","§7Off: playback starts where you stand right now.","§7Вимк: повтор почнеться там, де ви стоїте зараз.","§7Aus: die Wiedergabe startet dort, wo du gerade stehst.","§7Wył: powtórka zacznie się tam, gdzie teraz stoisz."),Lang.s("§8Нужен мод Baritone. Если дойти не выйдет, мод покажет метку и попросит встать на неё.","§8Requires Baritone. If it cannot walk there, the mod shows a marker and asks you to stand on it.","§8Потрібен мод Baritone. Якщо дійти не вийде, мод покаже мітку й попросить встати на неї.","§8Benötigt Baritone. Wenn es nicht hinkommt, zeigt die Mod eine Markierung und bittet dich, dich daraufzustellen.","§8Wymaga moda Baritone. Jeśli nie uda się dojść, mod pokaże znacznik i poprosi, by na nim stanąć.")));ty+=toggleH+5;
        cursor=dep(new StyledButton(CURSOR,left,ty,fullW,toggleH,Lang.s("Вернуть взгляд к первому кадру","Restore the view to the first frame","Повернути погляд до першого кадру","Blick auf den ersten Frame zurücksetzen","Przywróć wzrok do pierwszej klatki")).asToggle(config.isCursorStabilization()).tip(Lang.s("§fВзгляд как в начале записи","§fView as at the recording start","§fПогляд як на початку запису","§fBlick wie am Aufnahmebeginn","§fWzrok jak na początku nagrania"),Lang.s("§7Перед стартом камера один раз повернётся туда же, куда вы смотрели в начале записи.","§7Before the start the camera turns once to where you looked at the beginning of the recording.","§7Перед стартом камера один раз повернеться туди ж, куди ви дивилися на початку запису.","§7Vor dem Start dreht sich die Kamera einmal dorthin, wo du zu Beginn der Aufnahme hingeschaut hast.","§7Przed startem kamera raz obróci się tam, gdzie patrzyłeś na początku nagrania."),Lang.s("§7Работает и с возвратом, и без него.","§7Works both with and without the auto return.","§7Працює і з поверненням, і без нього.","§7Funktioniert mit und ohne Auto-Rückkehr.","§7Działa zarówno z powrotem, jak i bez niego."),Lang.s("§8Потом обзором управляете вы.","§8After that you control the view.","§8Потім оглядом керуєте ви.","§8Danach steuerst du die Sicht.","§8Potem widokiem sterujesz ty.")));ty+=toggleH+5;
        skip=add(new StyledButton(SKIP_DELAY,left,ty,fullW,toggleH,Lang.s("Отсчёт только перед 1-м циклом","Countdown before the 1st cycle only","Відлік лише перед 1-м циклом","Countdown nur vor dem 1. Durchlauf","Odliczanie tylko przed 1. cyklem")).asToggle(config.isSkipLoopStartDelay()).tip(Lang.s("§fОтсчёт перед кругами","§fCountdown before cycles","§fВідлік перед колами","§fCountdown vor den Runden","§fOdliczanie przed rundami"),Lang.s("§7Вкл: 3, 2, 1 только перед первым кругом.","§7On: 3, 2, 1 before the first cycle only.","§7Увімк: 3, 2, 1 лише перед першим колом.","§7An: 3, 2, 1 nur vor der ersten Runde.","§7Wł: 3, 2, 1 tylko przed pierwszą rundą."),Lang.s("§7Выкл: 3, 2, 1 перед каждым кругом.","§7Off: 3, 2, 1 before every cycle.","§7Вимк: 3, 2, 1 перед кожним колом.","§7Aus: 3, 2, 1 vor jeder Runde.","§7Wył: 3, 2, 1 przed każdą rundą."),Lang.s("§8Пригодится только при зацикливании.","§8Useful only when looping.","§8Знадобиться лише при зацикленні.","§8Nur beim Schleifen nützlich.","§8Przydatne tylko przy zapętlaniu.")));ty+=toggleH+13;
        paramTop=ty+11;rowH=18;int fy=y+h-26;paramStep=Math.max(19,Math.min(24,(fy-6-paramTop-rowH)/2));int step=paramStep;
        addStepper(POS_DEC,POS_INC,paramTop,Lang.s("Точность возврата","Return accuracy","Точність повернення","Rückkehr-Genauigkeit","Dokładność powrotu"),Lang.s("§7Насколько близко к точке старта нужно встать: 0.05-0.50 блока.","§7How close to the start point you must stand: 0.05-0.50 blocks.","§7Наскільки близько до точки старту треба встати: 0.05-0.50 блока.","§7Wie nah du am Startpunkt stehen musst: 0.05-0.50 Blöcke.","§7Jak blisko punktu startu musisz stanąć: 0.05-0.50 bloku."));addStepper(SPEED_DEC,SPEED_INC,paramTop+step,Lang.s("Скорость подхода","Approach speed","Швидкість підходу","Annäherungsgeschwindigkeit","Prędkość podejścia"),Lang.s("§7Как быстро идти на последних шагах: 0.2-1.0.","§7How fast to walk on the last steps: 0.2-1.0.","§7Як швидко йти на останніх кроках: 0.2-1.0.","§7Wie schnell auf den letzten Schritten gegangen wird: 0.2-1.0.","§7Jak szybko iść na ostatnich krokach: 0.2-1.0."));addStepper(TIME_DEC,TIME_INC,paramTop+step*2,Lang.s("Сколько ждать","How long to wait","Скільки чекати","Wie lange warten","Ile czekać"),Lang.s("§7Если дойти не вышло, мод бросит попытку: 15-180 сек.","§7If it cannot get there, the mod gives up: 15-180 sec.","§7Якщо дійти не вдалося, мод кине спробу: 15-180 сек.","§7Wenn es nicht hinkommt, gibt die Mod auf: 15-180 Sek.","§7Jeśli nie uda się dojść, mod przerwie próbę: 15-180 s."));
        int bw=(fullW-8)/2;add(new StyledButton(CANCEL,left,fy,bw,19,Lang.s("Отмена","Cancel","Скасувати","Abbrechen","Anuluj")).accent(UiTheme.GRAY).tip(Lang.s("§fОтмена","§fCancel","§fСкасувати","§fAbbrechen","§fAnuluj"),Lang.s("§7Вернёт значения, какие были при входе сюда.","§7Restores the values you had when you entered this screen.","§7Поверне значення, які були при вході сюди.","§7Stellt die Werte wieder her, die du beim Öffnen hattest.","§7Przywraca wartości z momentu wejścia tutaj.")));add(new StyledButton(SAVE,left+bw+8,fy,fullW-bw-8,19,Lang.s("Применить","Apply","Застосувати","Anwenden","Zastosuj")).primary().accent(UiTheme.GREEN).tip(Lang.s("§fПрименить","§fApply","§fЗастосувати","§fAnwenden","§fZastosuj"),Lang.s("§7Перенесёт эти значения в окно настроек.","§7Carries these values over to the settings window.","§7Перенесе ці значення у вікно налаштувань.","§7Überträgt diese Werte ins Einstellungsfenster.","§7Przeniesie te wartości do okna ustawień."),Lang.s("§8Чтобы сохранить насовсем, нажмите «Сохранить» в настройках.","§8To keep them for good, press Save in the settings.","§8Щоб зберегти назавжди, натисніть «Зберегти» у налаштуваннях.","§8Zum dauerhaften Speichern drücke «Speichern» in den Einstellungen.","§8Aby zapisać na stałe, naciśnij «Zapisz» w ustawieniach.")));sync();}
    private static float snap2(float v){return Math.round(v*100f)/100f;}private static float snap1(float v){return Math.round(v*10f)/10f;}
    private void sync(){master.setOn(config.isAutoReturnEnabled());cursor.setOn(config.isCursorStabilization());skip.setOn(config.isSkipLoopStartDelay());}
    @Override public void drawScreen(int mx,int my,float pt){{int bd=UiTheme.GLASS_BACKDROP;drawGradientRect(0,0,width,height,bd,bd);}UiTheme.window(x,y,x+w,y+h,30);int hx=x+14,hy=y+11;Gui.drawRect(hx,hy,hx+3,hy+10,UiTheme.ACCENT);UiTheme.drawFitted(fontRenderer,Lang.s("§lСтабилизация и автовозврат","§lStabilization and auto return","§lСтабілізація і автоповернення","§lStabilisierung und Auto-Rückkehr","§lStabilizacja i auto-powrót"),hx+9,hy,w-40,UiTheme.TEXT);UiTheme.sectionLabel(fontRenderer,Lang.s("ПОВЕДЕНИЕ","BEHAVIOR","ПОВЕДІНКА","VERHALTEN","ZACHOWANIE"),x+16,y+36,w-32);UiTheme.sectionLabel(fontRenderer,Lang.s("ДОВОДКА BARITONE","BARITONE APPROACH","ДОВЕДЕННЯ BARITONE","BARITONE-ANNÄHERUNG","DOPROWADZANIE BARITONE"),x+16,paramTop-12,w-32);String[] names={Lang.s("Точность позиции","Position accuracy","Точність позиції","Positionsgenauigkeit","Dokładność pozycji"),Lang.s("Скорость доводки","Approach speed","Швидкість доведення","Annäherungstempo","Prędkość doprowadzania"),Lang.s("Тайм-аут","Timeout","Тайм-аут","Timeout","Limit czasu")};String[] values={String.format(java.util.Locale.ROOT,"%.2f",config.getReturnPositionTolerance()),String.format(java.util.Locale.ROOT,"%.1f",config.getReturnAlignSpeed()),config.getReturnTimeoutSeconds()+Lang.s("с","s","с","s","s")};int step=paramStep,chip=58,bw=22,gap=4,right=x+w-16,chipX=right-bw-gap-chip;for(int i=0;i<3;i++){int ry=paramTop+step*i;UiTheme.drawFitted(fontRenderer,names[i],x+18,ry+5,Math.max(20,chipX-x-24),UiTheme.TEXT_DIM);UiTheme.inset(chipX,ry,chipX+chip,ry+rowH);UiTheme.drawCenteredFitted(fontRenderer,values[i],chipX+chip/2f,ry+5,chip-6,UiTheme.TEXT,false);}if(y+h-40>=paramTop+step*2+rowH+2)fontRenderer.drawString(changed()?Lang.s("§eЕсть несохранённые изменения","§eUnsaved changes","§eЄ незбережені зміни","§eUngespeicherte Änderungen","§eSą niezapisane zmiany"):Lang.s("§8Esc: отмена","§8Esc: cancel","§8Esc: скасувати","§8Esc: abbrechen","§8Esc: anuluj"),x+16,y+h-40,UiTheme.TEXT_MUTE);sync();super.drawScreen(mx,my,pt);for(GuiButton raw:buttonList)if(raw instanceof StyledButton){StyledButton b=(StyledButton)raw;if(b.visible&&b.isMouseOver()&&b.tooltip!=null){if(UiTheme.tipReady(b))UiTheme.tooltip(fontRenderer,b.tooltip,mx,my,width,height);break;}}}
    @Override protected void actionPerformed(GuiButton b)throws IOException{switch(b.id){case MASTER:config.setAutoReturnEnabled(!config.isAutoReturnEnabled());break;case CURSOR:config.setCursorStabilization(!config.isCursorStabilization());break;case SKIP_DELAY:config.setSkipLoopStartDelay(!config.isSkipLoopStartDelay());break;case POS_DEC:config.setReturnPositionTolerance(snap2(config.getReturnPositionTolerance()-0.01f));break;case POS_INC:config.setReturnPositionTolerance(snap2(config.getReturnPositionTolerance()+0.01f));break;case SPEED_DEC:config.setReturnAlignSpeed(snap1(config.getReturnAlignSpeed()-0.1f));break;case SPEED_INC:config.setReturnAlignSpeed(snap1(config.getReturnAlignSpeed()+0.1f));break;case TIME_DEC:config.setReturnTimeoutSeconds(config.getReturnTimeoutSeconds()-15);break;case TIME_INC:config.setReturnTimeoutSeconds(config.getReturnTimeoutSeconds()+15);break;case SAVE:saved=true;snapshot();mc.displayGuiScreen(parent);break;case CANCEL:restore();mc.displayGuiScreen(parent);break;}sync();}
    @Override protected void keyTyped(char c,int key)throws IOException{if(key==1){restore();mc.displayGuiScreen(parent);}else super.keyTyped(c,key);}
    @Override public void onGuiClosed(){if(!saved)restore();}
    @Override public boolean doesGuiPauseGame(){return false;}
}
