package com.mirror.recorder.storage;
import com.mirror.recorder.model.Frame;import net.minecraft.nbt.*;import net.minecraftforge.common.util.Constants;import org.apache.logging.log4j.*;import com.mirror.recorder.debug.MirrorDebug;import java.io.*;import java.text.SimpleDateFormat;import java.util.*;
public class StorageManager{
    private static final Logger LOG=LogManager.getLogger("MirrorRecorder/Storage");public static final int MAX_FRAMES=72000,FORMAT_VERSION=3,MAX_TRASH=100;private static final long MAX_FILE_BYTES=64L*1024L*1024L;private static final long MAX_NBT_BYTES=256L*1024L*1024L;private int lastSkippedFrames=0;private final File saveDir,exportDir,trashDir;private final Map<Integer,SlotSummary> summaries=new HashMap<Integer,SlotSummary>();private final Set<String> sessionTrash=new HashSet<String>();private final Map<String,TrashSummary> trashSummaries=new HashMap<String,TrashSummary>();
    public StorageManager(File minecraftDir){saveDir=new File(minecraftDir,"mirror_recorder");exportDir=new File(saveDir,"exports");trashDir=new File(saveDir,"trash");if(!saveDir.exists()&&!saveDir.mkdirs())LOG.error("Failed to create save directory");if(!exportDir.exists()&&!exportDir.mkdirs())LOG.error("Failed to create export directory");if(!trashDir.exists()&&!trashDir.mkdirs())LOG.error("Failed to create trash directory");loadSessionTrash();}
    private boolean validSlot(int s){return s>=1&&s<=100;}private File nbtFile(int s){return new File(saveDir,"slot_"+s+".nbt");}private File tmpFile(int s){return new File(saveDir,"slot_"+s+".tmp");}private File bakFile(int s){return new File(saveDir,"slot_"+s+".bak");}
    /** Сначала атомарное перемещение через NIO, затем обычное с заменой, и только потом renameTo. На ФС без ATOMIC_MOVE поведение остаётся как было. */
    private boolean moveFile(File from,File to){if(from==null||to==null||!from.isFile())return false;try{java.nio.file.Files.move(from.toPath(),to.toPath(),java.nio.file.StandardCopyOption.ATOMIC_MOVE);return true;}catch(Exception atomicUnsupported){try{java.nio.file.Files.move(from.toPath(),to.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);return true;}catch(Exception replaceFailed){return from.renameTo(to);}}}
    private boolean writeAtomically(int slot,NBTTagCompound root){if(!validSlot(slot)||root==null)return false;File tmp=tmpFile(slot),nbt=nbtFile(slot),bak=bakFile(slot);try{if(tmp.exists()&&!tmp.delete())return false;writeFast(root,tmp);if(!verifyStream(tmp)){LOG.error("Written file for slot {} failed verification, keeping the old one",slot);MirrorDebug.log("STORAGE","verification failed for slot "+slot+", backup untouched");tmp.delete();return false;}if(nbt.exists()){if(bak.exists()&&!bak.delete()){tmp.delete();return false;}if(!moveFile(nbt,bak)){tmp.delete();return false;}}if(!moveFile(tmp,nbt)){if(bak.exists())moveFile(bak,nbt);tmp.delete();return false;}invalidateSummary(slot);return true;}catch(Exception e){LOG.error("Atomic write failed for slot {}",slot,e);if(tmp.exists())tmp.delete();if(!nbt.exists()&&bak.exists())moveFile(bak,nbt);return false;}}
    public boolean saveRecording(int slot,List<Frame> frames,NBTTagCompound settings){if(!validSlot(slot)||frames==null||frames.isEmpty()||frames.size()>MAX_FRAMES){MirrorDebug.log("STORAGE","save rejected for slot "+slot+" (frames="+(frames==null?-1:frames.size())+", limit="+MAX_FRAMES+")");return false;}MirrorDebug.log("STORAGE","saving slot "+slot+", frames="+frames.size());NBTTagCompound root=new NBTTagCompound();root.setInteger("Version",FORMAT_VERSION);SlotSummary meta=summary(slot);if(!meta.name.isEmpty())root.setString("SlotName",meta.name);if(!meta.desc.isEmpty())root.setString("SlotDesc",meta.desc);NBTTagList list=new NBTTagList();for(Frame f:frames){if(!validFrame(f))return false;list.appendTag(f.toNBT());}root.setInteger("FrameCount",list.tagCount());root.setTag("Frames",list);if(settings!=null)root.setTag("SlotSettings",settings);boolean ok=writeAtomically(slot,root);if(!ok)LOG.error("Failed to save slot {}",slot);return ok;}
    /** Мягкое сохранение: невалидные кадры пропускаются, как при чтении. Вызывается как запасной путь при остановке записи. */
    public boolean saveRecordingLenient(int slot,List<Frame> frames,NBTTagCompound settings){
        if(!validSlot(slot)||frames==null||frames.isEmpty()||frames.size()>MAX_FRAMES)return false;
        NBTTagCompound root=new NBTTagCompound();root.setInteger("Version",FORMAT_VERSION);
        SlotSummary meta=summary(slot);if(!meta.name.isEmpty())root.setString("SlotName",meta.name);if(!meta.desc.isEmpty())root.setString("SlotDesc",meta.desc);
        NBTTagList list=new NBTTagList();int skipped=0;for(Frame f:frames){if(validFrame(f))list.appendTag(f.toNBT());else skipped++;}
        if(list.tagCount()==0)return false;
        if(skipped>0)LOG.warn("Slot {}: saved {}/{} frames ({} skipped)",slot,list.tagCount(),frames.size(),skipped);
        root.setInteger("FrameCount",list.tagCount());root.setTag("Frames",list);if(settings!=null)root.setTag("SlotSettings",settings);
        return writeAtomically(slot,root);
    }
    /** Порядок: целый .nbt -> целый .bak -> частично уцелевшие кадры. Один битый кадр больше не обнуляет всю запись. */
    public List<Frame> loadRecording(int slot){if(!validSlot(slot))return new ArrayList<Frame>();List<Frame> main=decodeRoot(tryRead(nbtFile(slot)));int mainSkipped=lastSkippedFrames;if(main!=null&&mainSkipped==0)return main;List<Frame> bak=decodeRoot(tryRead(bakFile(slot)));int bakSkipped=lastSkippedFrames;if(bak!=null&&bakSkipped==0){LOG.warn("Recovered slot {} from validated backup",slot);MirrorDebug.log("STORAGE","slot "+slot+": main file damaged, recovered "+bak.size()+" frames from .bak");return bak;}if(main!=null&&(bak==null||main.size()>=bak.size())){LOG.warn("Slot {} loaded with {} damaged frames skipped",slot,mainSkipped);MirrorDebug.log("STORAGE","slot "+slot+": kept "+main.size()+" frames, skipped "+mainSkipped+" damaged");return main;}if(bak!=null){LOG.warn("Slot {} loaded from .bak with {} damaged frames skipped",slot,bakSkipped);MirrorDebug.log("STORAGE","slot "+slot+": kept "+bak.size()+" frames from .bak, skipped "+bakSkipped+" damaged");return bak;}MirrorDebug.log("STORAGE","slot "+slot+": no readable recording in .nbt or .bak");return new ArrayList<Frame>();}
    public int peekFrameCount(int slot){return summary(slot).count;}
    public boolean deleteRecording(int slot){if(!validSlot(slot))return false;NBTTagCompound best=bestRootForBackup(slot);if(best!=null){File out=new File(trashDir,"slot-"+slot+"-"+new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date())+".mrr");int suffix=2;while(out.exists())out=new File(trashDir,"slot-"+slot+"-"+new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date())+"-"+(suffix++)+".mrr");try(FileOutputStream fos=new FileOutputStream(out)){best.setInteger("TrashSlot",slot);best.setLong("TrashedAt",System.currentTimeMillis());CompressedStreamTools.writeCompressed(best,fos);sessionTrash.add(out.getName());saveSessionTrash();}catch(Exception e){LOG.error("Trash copy failed for slot {}",slot,e);return false;}}File t=tmpFile(slot),b=bakFile(slot),n=nbtFile(slot);if(n.exists()&&!n.delete())return false;boolean ok=!t.exists()||t.delete();if(b.exists()&&!b.delete())ok=false;invalidateSummary(slot);return ok;}
    public String loadSlotName(int s){return summary(s).name;}public String loadSlotDesc(int s){return summary(s).desc;}
    public NBTTagCompound loadSlotSettings(int slot){NBTTagCompound r=readStructuralRoot(slot);return r!=null&&r.hasKey("SlotSettings",Constants.NBT.TAG_COMPOUND)?r.getCompoundTag("SlotSettings"):null;}
    public boolean saveSlotSettings(int slot,NBTTagCompound settings){if(settings==null)return false;NBTTagCompound r=readStructuralRoot(slot);if(r==null)return false;r.setTag("SlotSettings",settings);return writeAtomically(slot,r);}
    public boolean saveSlotMetadata(int slot,String name,String desc){NBTTagCompound r=readStructuralRoot(slot);if(r==null)return false;r.setString("SlotName",clean(name,40));r.setString("SlotDesc",clean(desc,120));return writeAtomically(slot,r);}
    /** Строки локализации приходят параметрами: слой хранилища не знает о слое интерфейса. */
    public boolean duplicateRecording(int source,int target,String emptyLabel,String copySuffix){if(!validSlot(source)||!validSlot(target)||source==target||peekFrameCount(target)>0)return false;NBTTagCompound r=readStructuralRoot(source);if(r==null)return false;String sourceName=clean(r.getString("SlotName"),40);if(sourceName.isEmpty()){r.setString("SlotName",clean(emptyLabel,40));return writeAtomically(target,r);}
        // У копии всегда отличимое имя: базовое имя + пометка «копия». При копии копии пометка не накапливается.
        String suffix=copySuffix==null?"":copySuffix;String base=sourceName;while(!suffix.isEmpty()&&base.endsWith(suffix))base=base.substring(0,base.length()-suffix.length()).trim();if(base.length()+suffix.length()>40)base=base.substring(0,Math.max(0,40-suffix.length())).trim();r.setString("SlotName",base+suffix);return writeAtomically(target,r);}
    public String exportRecording(int slot){NBTTagCompound r=readStructuralRoot(slot);if(r==null)return null;String base=safeName(clean(r.getString("SlotName"),40));if(base.isEmpty())base="slot_"+slot;String stamp=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date());File out=new File(exportDir,base+"-slot-"+slot+"-"+stamp+".mrr");int suffix=2;while(out.exists())out=new File(exportDir,base+"-slot-"+slot+"-"+stamp+"-"+(suffix++)+".mrr");try(FileOutputStream fos=new FileOutputStream(out)){r.setLong("ExportedAt",System.currentTimeMillis());CompressedStreamTools.writeCompressed(r,fos);return out.getName();}catch(Exception e){LOG.error("Export failed for slot {}",slot,e);return null;}}
    public List<String> listExportFiles(){File[] files=exportDir.listFiles(new FilenameFilter(){public boolean accept(File d,String n){return n.toLowerCase(Locale.ROOT).endsWith(".mrr");}});List<File> all=new ArrayList<File>();if(files!=null)Collections.addAll(all,files);Collections.sort(all,new Comparator<File>(){public int compare(File a,File b){return Long.compare(b.lastModified(),a.lastModified());}});List<String> names=new ArrayList<String>();for(File f:all)if(f.isFile())names.add(f.getName());return names;}
    public boolean importRecording(int slot,String fileName){if(!validSlot(slot)||peekFrameCount(slot)>0||fileName==null)return false;File in=new File(exportDir,new File(fileName).getName());NBTTagCompound r=tryRead(in);if(!validRoot(r))return false;r.setInteger("Version",Math.max(1,Math.min(FORMAT_VERSION,r.hasKey("Version")?r.getInteger("Version"):2)));r.setInteger("FrameCount",r.getTagList("Frames",Constants.NBT.TAG_COMPOUND).tagCount());r.setBoolean("Imported",true);return writeAtomically(slot,r);}
    public long getLastModified(int slot){if(!validSlot(slot))return 0L;File f=nbtFile(slot);if(!f.isFile())f=bakFile(slot);return f.isFile()?f.lastModified():0L;}public long getFileSize(int slot){if(!validSlot(slot))return 0L;File f=nbtFile(slot);if(!f.isFile())f=bakFile(slot);return f.isFile()?f.length():0L;}public String getExportDirectoryPath(){return exportDir.getAbsolutePath();}
    private SlotSummary summary(int slot){if(!validSlot(slot))return SlotSummary.EMPTY;File n=nbtFile(slot),b=bakFile(slot);long ns=n.isFile()?n.lastModified():0L,nz=n.isFile()?n.length():0L,bs=b.isFile()?b.lastModified():0L,bz=b.isFile()?b.length():0L;SlotSummary old=summaries.get(slot);if(old!=null&&old.matches(ns,nz,bs,bz))return old;NBTTagCompound root=readStructuralRoot(slot);SlotSummary fresh=root==null?new SlotSummary(ns,nz,bs,bz,0,"","",false):new SlotSummary(ns,nz,bs,bz,root.getTagList("Frames",Constants.NBT.TAG_COMPOUND).tagCount(),clean(root.getString("SlotName"),40),clean(root.getString("SlotDesc"),120),root.getBoolean("Imported"));summaries.put(slot,fresh);return fresh;}
    private void invalidateSummary(int slot){summaries.remove(slot);}
    private static final class SlotSummary{static final SlotSummary EMPTY=new SlotSummary(0L,0L,0L,0L,0,"","",false);final long ns,nz,bs,bz;final int count;final String name,desc;final boolean imported;SlotSummary(long ns,long nz,long bs,long bz,int count,String name,String desc,boolean imported){this.ns=ns;this.nz=nz;this.bs=bs;this.bz=bz;this.count=count;this.name=name;this.desc=desc;this.imported=imported;}boolean matches(long nst,long nsz,long bst,long bsz){return ns==nst&&nz==nsz&&bs==bst&&bz==bsz;}}
    private NBTTagCompound readStructuralRoot(int slot){if(!validSlot(slot))return null;NBTTagCompound r=tryRead(nbtFile(slot));if(validStructure(r))return r;NBTTagCompound b=tryRead(bakFile(slot));return validStructure(b)?b:null;}
    /** Ограниченное чтение: лимит есть и на размер файла, и на объём распакованного NBT: специально сжатый .mrr больше не съест память. */
    private NBTTagCompound tryRead(File f){if(f==null||!f.isFile()||f.length()<=0L||f.length()>MAX_FILE_BYTES)return null;try(DataInputStream in=new DataInputStream(new BufferedInputStream(new java.util.zip.GZIPInputStream(new FileInputStream(f)),16384))){return CompressedStreamTools.read(in,new NBTSizeTracker(MAX_NBT_BYTES));}catch(Exception e){LOG.error("Read error for {}",f.getName(),e);return null;}}
    /** Запись с быстрым сжатием: файл чуть больше, зато остановка длинной записи не подвешивает клиент. */
    private void writeFast(NBTTagCompound root,File file)throws IOException{try(FileOutputStream fos=new FileOutputStream(file);FastGzip gz=new FastGzip(fos);DataOutputStream out=new DataOutputStream(gz)){CompressedStreamTools.write(root,out);}}
    private static final class FastGzip extends java.util.zip.GZIPOutputStream{FastGzip(OutputStream out)throws IOException{super(out,16384);def.setLevel(java.util.zip.Deflater.BEST_SPEED);}}
    /** Проверка записанного файла потоком, без сборки NBT-дерева: ловит обрыв и битый gzip. */
    private boolean verifyStream(File f){if(f==null||!f.isFile()||f.length()<=0L||f.length()>MAX_FILE_BYTES)return false;try(java.util.zip.GZIPInputStream in=new java.util.zip.GZIPInputStream(new BufferedInputStream(new FileInputStream(f)),16384)){byte[] buf=new byte[16384];long total=0L;int n;while((n=in.read(buf))>=0){total+=n;if(total>MAX_NBT_BYTES)return false;}return total>0L;}catch(Exception e){LOG.error("Verification read failed for {}",f.getName(),e);return false;}}
    /** Запись пришла извне (импорт или её копия). */
    public boolean isImportedRecording(int slot){return validSlot(slot)&&summary(slot).imported;}
    /** FrameCount — подсказка, а не приговор: расхождение с фактическим числом кадров больше не делает слот пустым. */
    private boolean validStructure(NBTTagCompound r){if(r==null)return false;int v=r.hasKey("Version")?r.getInteger("Version"):0;if(v<0||v>FORMAT_VERSION)return false;NBTTagList list=r.getTagList("Frames",Constants.NBT.TAG_COMPOUND);int actual=list.tagCount();return actual>=1&&actual<=MAX_FRAMES;}
    private List<Frame> decodeRoot(NBTTagCompound r){lastSkippedFrames=0;if(!validStructure(r))return null;NBTTagList list=r.getTagList("Frames",Constants.NBT.TAG_COMPOUND);List<Frame> out=new ArrayList<Frame>(list.tagCount());int skipped=0;boolean screenState=(r.hasKey("Version")?r.getInteger("Version"):0)>=3;for(int i=0;i<list.tagCount();i++){try{Frame f=Frame.fromNBT(list.getCompoundTagAt(i),screenState);if(validFrame(f))out.add(f);else skipped++;}catch(Exception e){skipped++;}}lastSkippedFrames=skipped;return out.isEmpty()?null:out;}
    private boolean validRoot(NBTTagCompound r){if(!validStructure(r))return false;NBTTagList list=r.getTagList("Frames",Constants.NBT.TAG_COMPOUND);for(int i=0;i<list.tagCount();i++){try{if(!validFrame(Frame.fromNBT(list.getCompoundTagAt(i))))return false;}catch(Exception e){return false;}}return true;}
    private boolean validFrame(Frame f){return (f!=null&&finite(f.x)&&finite(f.y)&&finite(f.z)&&Math.abs(f.x)<=31000000d&&Math.abs(f.y)<=31000000d&&Math.abs(f.z)<=31000000d&&finite(f.motionX)&&finite(f.motionY)&&finite(f.motionZ)&&Math.abs(f.motionX)<=100d&&Math.abs(f.motionY)<=100d&&Math.abs(f.motionZ)<=100d&&finite(f.yaw)&&finite(f.pitch)&&Math.abs(f.pitch)<=90.001f&&finite(f.moveForward)&&finite(f.moveStrafe)&&Math.abs(f.moveForward)<=1.001f&&Math.abs(f.moveStrafe)<=1.001f&&f.tickIndex>=0&&f.tickIndex<MAX_FRAMES&&f.keyMask>=0&&f.hotbarSlot>=-1&&f.hotbarSlot<=8&&finite(f.dYaw)&&finite(f.dPitch)&&Math.abs(f.dYaw)<=360.001f&&Math.abs(f.dPitch)<=180.001f&&(f.chatMessage==null||f.chatMessage.length()<=256)&&(!f.guiClick||(finite(f.guiX)&&finite(f.guiY)&&f.guiX>=0f&&f.guiX<=1f&&f.guiY>=0f&&f.guiY<=1f&&f.guiScreen!=null&&f.guiScreen.length()>0&&f.guiScreen.length()<=160&&Math.abs(f.guiCenterX)<=16384&&Math.abs(f.guiCenterY)<=16384)))&&f.keyEvents!=null&&f.keyEvents.length%2==0&&f.keyEvents.length<=Frame.MAX_KEY_EVENTS*2&&finite(f.curX)&&finite(f.curY)&&Math.abs(f.curX)<=16384f&&Math.abs(f.curY)<=16384f&&(!f.hasTarget||(Math.abs(f.tgtX)<=31000000&&Math.abs(f.tgtY)<=31000000&&Math.abs(f.tgtZ)<=31000000&&f.tgtFace>=-1&&f.tgtFace<=5&&finite(f.hitX)&&finite(f.hitY)&&finite(f.hitZ)));}private boolean finite(double v){return !Double.isNaN(v)&&!Double.isInfinite(v);}
    private String clean(String v,int max){if(v==null)return"";StringBuilder b=new StringBuilder();for(int i=0;i<v.length()&&b.length()<max;i++){char c=v.charAt(i);if(c!='\u00a7'&&!Character.isISOControl(c))b.append(c);}return b.toString().trim();}private String safeName(String v){StringBuilder b=new StringBuilder();for(int i=0;i<v.length()&&b.length()<28;i++){char c=v.charAt(i);b.append(Character.isLetterOrDigit(c)||c=='-'||c=='_'?c:'_');}return b.toString().replaceAll("_+","_");}
    private File trashFile(String name){return name==null?null:new File(trashDir,new File(name).getName());}
    private NBTTagCompound trashRoot(String name){File f=trashFile(name);if(f==null||!f.isFile())return null;NBTTagCompound r=tryRead(f);return validRoot(r)?r:null;}
    public boolean moveToTrash(int slot){NBTTagCompound r=readStructuralRoot(slot);if(r==null)return false;r.setInteger("TrashSlot",slot);r.setLong("TrashedAt",System.currentTimeMillis());String stamp=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date());File out=new File(trashDir,"slot-"+slot+"-"+stamp+".mrr");int suffix=2;while(out.exists())out=new File(trashDir,"slot-"+slot+"-"+stamp+"-"+(suffix++)+".mrr");try(FileOutputStream fos=new FileOutputStream(out)){CompressedStreamTools.writeCompressed(r,fos);}catch(Exception e){LOG.error("Trash copy failed for slot {}",slot,e);return false;}sessionTrash.add(out.getName());saveSessionTrash();MirrorDebug.log("TRASH","slot "+slot+" copied to "+out.getName());trimTrash();return true;}
    private void trimTrash(){List<String> all=listTrashFiles();for(int i=MAX_TRASH;i<all.size();i++){File f=trashFile(all.get(i));if(f!=null&&f.isFile()&&f.delete())forgetTrash(f.getName());}}
    public List<String> listTrashFiles(){File[] files=trashDir.listFiles(new FilenameFilter(){public boolean accept(File d,String n){return n.toLowerCase(Locale.ROOT).endsWith(".mrr");}});List<File> all=new ArrayList<File>();if(files!=null)Collections.addAll(all,files);Collections.sort(all,new Comparator<File>(){public int compare(File a,File b){return Long.compare(b.lastModified(),a.lastModified());}});List<String> names=new ArrayList<String>();for(File f:all)if(f.isFile())names.add(f.getName());return names;}
    /** Метаданные корзины: один разбор файла вместо четырёх, кэш по времени и размеру -- тот же приём, что summary(slot) для слотов. Полная проверка кадров остаётся в restoreTrash. */
    private TrashSummary trashSummary(String name){File f=trashFile(name);if(f==null||!f.isFile())return null;String key=f.getName();long st=f.lastModified(),sz=f.length();TrashSummary old=trashSummaries.get(key);if(old!=null&&old.matches(st,sz))return old;NBTTagCompound r=tryRead(f);if(!validStructure(r))r=null;TrashSummary fresh=r==null?new TrashSummary(st,sz,0,0,0L,""):new TrashSummary(st,sz,r.getInteger("TrashSlot"),r.getTagList("Frames",Constants.NBT.TAG_COMPOUND).tagCount(),r.hasKey("TrashedAt")?r.getLong("TrashedAt"):0L,clean(r.getString("SlotName"),40));trashSummaries.put(key,fresh);return fresh;}
    private static final class TrashSummary{final long stamp,size,trashedAt;final int slot,frames;final String title;TrashSummary(long stamp,long size,int slot,int frames,long trashedAt,String title){this.stamp=stamp;this.size=size;this.slot=slot;this.frames=frames;this.trashedAt=trashedAt;this.title=title;}boolean matches(long s,long z){return stamp==s&&size==z;}}
    private void forgetTrash(String fileName){if(fileName==null)return;sessionTrash.remove(fileName);saveSessionTrash();trashSummaries.remove(fileName);}
    public int trashSlot(String name){TrashSummary t=trashSummary(name);return t==null?0:t.slot;}
    public int trashFrames(String name){TrashSummary t=trashSummary(name);return t==null?0:t.frames;}
    public long trashTime(String name){TrashSummary t=trashSummary(name);if(t==null)return 0L;return t.trashedAt>0L?t.trashedAt:t.stamp;}
    public String trashTitle(String name){TrashSummary t=trashSummary(name);return t==null?"":t.title;}
    /** Корзина -- обычная папка на диске, туда может попасть чужой .mrr. Доверяем только копии, которую мод сам создал в этой сессии; всё остальное восстанавливается с флагом Imported, то есть без права писать в чат и выполнять команды от имени игрока. Существующий флаг никогда не снимается. */
    public boolean restoreTrash(String name,int slot){if(!validSlot(slot)||peekFrameCount(slot)>0)return false;File f=trashFile(name);if(f==null||!f.isFile())return false;String key=f.getName();NBTTagCompound r=trashRoot(name);if(r==null)return false;r.removeTag("TrashSlot");r.removeTag("TrashedAt");r.setInteger("Version",Math.max(1,Math.min(FORMAT_VERSION,r.hasKey("Version")?r.getInteger("Version"):2)));r.setInteger("FrameCount",r.getTagList("Frames",Constants.NBT.TAG_COMPOUND).tagCount());boolean ownCopy=wasSessionTracked(key);if(!ownCopy)r.setBoolean("Imported",true);if(!writeAtomically(slot,r))return false;forgetTrash(key);if(f.isFile())f.delete();MirrorDebug.log("TRASH","restored "+key+" into slot "+slot+(ownCopy?" (own copy)":" (foreign file: chat and commands disabled)"));return true;}
    public boolean deleteTrash(String name){File f=trashFile(name);if(f==null||!f.isFile()||!f.delete())return false;forgetTrash(f.getName());return true;}
    public boolean clearTrash(){boolean ok=true;for(String n:listTrashFiles()){File f=trashFile(n);if(f==null)continue;if(f.isFile()&&!f.delete())ok=false;else forgetTrash(f.getName());}return ok;}
    public String latestTrashFile(){List<String> all=listTrashFiles();return all.isEmpty()?null:all.get(0);}
    public String getTrashDirectoryPath(){return trashDir.getAbsolutePath();}
    /** Файл сессии: имена файлов корзины, созданные в текущей сессии. Переживает перезапуск игры. */
    private File sessionStateFile(){return new File(saveDir,".trash_session");}
    private void loadSessionTrash(){File sf=sessionStateFile();if(!sf.isFile())return;try(BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(sf),"UTF-8"))){String line;while((line=r.readLine())!=null){String t=line.trim();if(!t.isEmpty())sessionTrash.add(t);}}catch(Exception e){LOG.error("Failed to load session trash state",e);}}
    private void saveSessionTrash(){try(BufferedWriter w=new BufferedWriter(new OutputStreamWriter(new FileOutputStream(sessionStateFile()),"UTF-8"))){for(String name:sessionTrash){w.write(name);w.newLine();}}catch(Exception e){LOG.error("Failed to save session trash state",e);}}
    /** Проверка: файл был создан в одной из прошлых сессий (persisted). */
    private boolean wasSessionTracked(String key){return sessionTrash.contains(key);}
    /** Лучшая доступная копия слота для архивации в корзину: предпочитаем .bak (целое предыдущее поколение), затем .nbt. */
    private NBTTagCompound bestRootForBackup(int slot){
        NBTTagCompound n=tryRead(nbtFile(slot));
        List<Frame> nFrames=n!=null&&validStructure(n)?decodeRoot(n):null;int nSkipped=lastSkippedFrames;
        if(nFrames!=null&&nSkipped==0)return n;
        NBTTagCompound b=tryRead(bakFile(slot));
        List<Frame> bFrames=b!=null&&validStructure(b)?decodeRoot(b):null;int bSkipped=lastSkippedFrames;
        if(bFrames!=null&&bSkipped==0)return b;
        if(nFrames!=null&&(bFrames==null||nFrames.size()>bFrames.size()||(nFrames.size()==bFrames.size()&&nSkipped<=bSkipped)))return n;
        return b!=null?b:n;
    }
}
